### PR TITLE
skip zero length strings in ERB template output

### PR DESCRIPTION
**Pull request by bdellegrazie**
Ensure that rocommunity and friends can be explicitly disabled
by setting them to the empty string (not undefined).

Solves #36

### CODE REVIEW

**Comment by razorsedge** [comment]
Would it be possible to resubmit this PR against razorsedge:develop?

**Comment by bdellegrazie** [comment]
Hi Mike,

Sure, the only thing is it fails on Ruby 1.8.x (i.e. the template breaks).
Its pretty simple I just don't know how to solve the problem with the
earlier version of Ruby.
I'll get to it sometime this weekend.

Thanks,

Brett

On 20 March 2015 at 06:41, Mike Arnold <notifications@github.com> wrote:

> Would it be possible to resubmit this PR against razorsedge:develop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/razorsedge/puppet-snmp/pull/37#issuecomment-83939470>.
>



-- 
Kind regards,

Brett Delle Grazie

**Comment by razorsedge** [comment]
Possibly try .length instead of .size?

**Comment by razorsedge** [comment]
Actually, strike that.  The Travis failures are due to the use of rspec 3 on Ruby 1.8.7.  I have fixed that error in razorsedge:develop.

**Comment by bdellegrazie** [comment]
Cool, I'll rebase sometime this weekend.

Cheers,

Brett

On 20 March 2015 at 07:22, Mike Arnold <notifications@github.com> wrote:

> Actually, strike that. The Travis failures are due to the use of rspec 3
> on Ruby 1.8.7. I have fixed that error in razorsedge:develop.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/razorsedge/puppet-snmp/pull/37#issuecomment-83942438>.
>



-- 
Kind regards,

Brett Delle Grazie

**Comment by bdellegrazie** [comment]
or now :)

On 20 March 2015 at 07:23, Brett Delle Grazie <brett.dellegrazie@gmail.com>
wrote:

> Cool, I'll rebase sometime this weekend.
>
> Cheers,
>
> Brett
>
> On 20 March 2015 at 07:22, Mike Arnold <notifications@github.com> wrote:
>
>> Actually, strike that. The Travis failures are due to the use of rspec 3
>> on Ruby 1.8.7. I have fixed that error in razorsedge:develop.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/razorsedge/puppet-snmp/pull/37#issuecomment-83942438>
>> .
>>
>
>
>
> --
> Kind regards,
>
> Brett Delle Grazie
>



-- 
Kind regards,

Brett Delle Grazie

**Comment by razorsedge** [comment]
Rebasing makes things worse. :-(  GitHub does not let you change the target.  You will have to close this PR and submit a new one.

**Comment by bdellegrazie** [comment]
Closing as requested, will reopen again

**Comment by bdellegrazie** [comment]
Reopened as #41

**Pull request closed without merging**
