### PR TITLE
Add support for OpenBSD

### PR DESCRIPTION
**Pull request by buzzdeee**
This adds OpenBSD to the supported operating systems, similar to the FreeBSD
support. Added spec tests for OpenBSD and mention it in README and
metadata.json.

Note that travis-ci seems to have problems with the Ruby 1.8 tests, which as far as I can
see are not related to the PR. The other spec tests are fine.

Hope this can be considered for merge. If there is something to enhance/fix etc. please let me know and I'll take care.

cheers

### CODE REVIEW

**Comment by buzzdeee** [comment]
figured I had a wrong owner of /var/net-snmp just fixed it

**Comment by razorsedge** [comment]
@buzzdeee Thank you for your submission. As per the DEVELOP.md file, could you please resubmit from the `develop` branch?

**Comment by buzzdeee** [comment]
Doh!, I'll see to get it done as soon as possible

**Comment by buzzdeee** [comment]
See PR #74 don't know how to change that on an existing PR here.

**Pull request closed without merging**
