### PR TITLE
Update for travis-ci not having proper rake version

### PR DESCRIPTION
**Pull request by mterzo**
Expanding the testing for puppet-snmp, i'm also allowing for now that enabling strict fails.

### CODE REVIEW

**Comment by razorsedge** [comment]
Closing this PR as #71 duplicates this commit.

**Comment by mterzo** [comment]
I made this commit by itself since it only had the Travis changes. Completely missed your develop.md.

**Comment by razorsedge** [comment]
@mterzo I would be happy with a PR that fixed any current Travis issues with rake/json/etc [no longer working](https://travis-ci.org/razorsedge/puppet-snmp/builds/158125676) and also added support for STRICT_VARIABLES.  I would suggest not trying to support every minor version of Puppet (3.6, 3.7, 3.8). See [puppetlabs-mysql](https://github.com/puppetlabs/puppetlabs-mysql/blob/master/.travis.yml) for possible inspiration.

**Comment by mterzo** [comment]
I'm not sure where to make the PR for that, now that I understand that you are using msync. That would effect all your modules.  Not just this one.

**Comment by razorsedge** [comment]
https://github.com/razorsedge/modulesync_configs or use the .sync.yml in this module to add overrides.

**Pull request closed without merging**
