### PR TITLE
Conglomerate of PRs with tests

### PR DESCRIPTION
**Pull request by jrwesolo**
I was looking at this module and saw a few open pull requests that seem to have been abandoned by their submitters. I went ahead and implemented some of the changes, complete with tests, for the following PRs: #29, #43, #49.

**Highlights**
* Simplify the snmpd.conf template with some ruby magic
* Allow the community and network variables to be strings or arrays
* Change default groups to be empty, prevent DDoS
* Allow `service_config_perms` to be a class parameter
* Validate additional arrays in `init` class
* Add test coverage for new code as well as some old code

### CODE REVIEW

**Comment by jrwesolo** [comment]
@razorsedge How's this look? I made the modifications you requests with #61.

**Comment by jrwesolo** [comment]
@razorsedge Does this need anything else before you can merge it in?

**Comment by razorsedge** [comment]
@jrwesolo Those "Merge branch" commits should not be in there.  Did you fork from `develop` or `master`?

**Comment by razorsedge** [comment]
Also, I am not a fan of PR#43, as it changes long-standing defaults without documenting them.  I fail to see how it helps prevent DDoS.

**Comment by jrwesolo** [comment]
Yes, I branched from master. Let me clean that up and do some quick research about PR#43. If I can find a good reason for it, I'll get that info to you. Otherwise, I'll remove that. Standby.

**Comment by jrwesolo** [comment]
@razorsedge Should be good now. I cleaned up the commits and removed the stuff from PR#43.

**Comment by razorsedge** [comment]
Closes #29 and #49.

**Comment by razorsedge** [comment]
Version [3.6.0](https://forge.puppetlabs.com/razorsedge/snmp/3.6.0/readme) released to the Forge.

**Pull request merged**
