### PR TITLE
Enable strict

### PR DESCRIPTION
**Pull request by mterzo**
This is go on top of the travis changes to do more strict testing.

### CODE REVIEW

**Comment by mterzo** [comment]
Fixes #65

**Comment by walkamongus** [comment]
+1 -- getting these errors as well

**Comment by cdenneen** [comment]
@razorsedge any eta on merging this?

**Comment by mterzo** [comment]
@razorsedge, do you want to continue to maintain this module?

**Comment by razorsedge** [comment]
@mterzo, What I want and what my two young children demand are presently in conflict.  :-(  Needless to say, when I have the time I don't have the energy and when I have the energy, I don't have the time.

As for this PR, I see a few issues:

1. I use [modulesync](https://github.com/voxpupuli/modulesync) for the .travis.yml.  Edit .sync.yml for any overrides.
1. Please read through the DEVELOP.md file.  It will tell you to branch from `develop` and not `master`.
1. Fact `::operatingsystemmajrelease` does not exist in all versions of Puppet that this module supports.
1. But mainly, params.pp is never a parameterized class.  If the world needs strict_variable support, PR #21 is going to be the way to do it.

**Comment by mterzo** [comment]
We all have busy lives. 

I honestly don't know what I was thinking. 

We need to get strict support for puppet 4. I'll rework it this a bit and resubmit.

**Comment by cdenneen** [comment]
@mterzo I would probably use puppetlabs/ntp as example and not parameterize the params class. 
@razorsedge thanks for the update, I don't think anything was meant by the question, also with so many modules moving over to the voxpupuli namespace, I think lately all public modules are starting to be asked this a lot. Allows for you to maintain it still but gives you help as well.

**Comment by razorsedge** [comment]
@mterzo @cdenneen No worries.  I've had a pretty horrible year with all sorts of life events.  I look at my growing mountain of PRs and issues and don't know where to start.  I did seriously consider donating to Puppet Community/voxpupuli when they were first created.

**Comment by mterzo** [comment]
They so good work.  It would definitely help with keeping the dependencies up-to-date.  I checked out voxpupuli's msync and they have dropped support for older versions of ruby.

**Comment by mterzo** [comment]
@cdenneen I thought I had followed ntp and others.  i think I cherry-picked the wrong commit. When making the branch.

**Pull request closed without merging**
