### PR TITLE
Change OS majdistrelease comparison to integer comparison

### PR DESCRIPTION
**Pull request by deepakhj**
Change OS majdistrelease comparison to integer comparison. Otherwise I get an error, comparison of String with 5 failed at.

### CODE REVIEW

**Comment by deepakhj** [comment]
Now I realize why I changed that to a regex. 

The previous line:
$majdistrelease = regsubst($::operatingsystemrelease,'^(\d+)\.(\d+)','\1') 

Sets majdistrelease to a string. So comparing that to an integer wouldn't work.

**Comment by razorsedge** [comment]
What version of Puppet are you using?

**Comment by deepakhj** [comment]
Puppet 3.7 and cantos 7. There's already fact for the major release.

**Comment by razorsedge** [comment]
And Ruby 2.0 on EL7....  Are you using future parser?

I am trying to determine what has changed to expose this error and Ruby 2.0 may be it.

**Comment by razorsedge** [comment]
That is what [Travis](https://travis-ci.org/razorsedge/puppet-snmp/jobs/55199760) is leading me to believe.

**Comment by deepakhj** [comment]
We're using the default ruby with RHEL7:
ruby 2.0.0p353 (2013-11-22) [x86_64-linux]

**Comment by razorsedge** [comment]
I have tested on a CentOS 7.0 VM with Puppet 3.7.4 using `puppet apply` and am not seeing this error.  I am guessing that you are using an agent/master configuration?  Can you tell me about your Puppetmaster?  Is it also CentOS 7/Puppet 3.7.4?  Are you using webrick, passenger, or puppet-server?

**Comment by deepakhj** [comment]
Looks like it works on my Centos 7 VM but does not work with my profile's rspec test. With this error:

"Puppet::Error: comparison of String with 5 failed at"

I'm running the rspec tests on my Mac (Yosemite), ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.1.0], Puppet 3.7.4, rspec-puppet 2.0.1.

**Comment by razorsedge** [comment]
Are you using rspec 2 or rspec 3?  Try running `bundle install && bundle exec rake spec` from the develop branch.

**Comment by deepakhj** [comment]
Pulling your module down and running the tests worked fine.

This is the test we're using for our base class which calls snmp.

require 'spec_helper'

describe 'profile::base', :type => :class do

  let(:facts) do {
    :hostname                   => 'ios2',
    :osfamily                   => 'RedHat',
    :operatingsystem            => 'RedHat',
    :operatingsystemrelease     => '6.3',
    :operatingsystemmajrelease  => '6',
  }
  end

  context 'with defaults for all parameters' do
    it { is_expected.to create_class('profile::base') }
    it { should contain_class('nrpe') }
    it { should contain_class('snmp') }

  end

end

**Comment by razorsedge** [comment]
@deepakhj I do not follow.  What does your profile::base class have to do with the snmp module?  Are you getting an error with the snmp module's rspec tests or the profile::base rspec tests?  Are you using rspec 2 or rspec 3?

**Comment by deepakhj** [comment]
Changed my fact definition from :operatingsystemrelease => '6.3', to :operatingsystemrelease => 6.3, and switched my .fixtures.yml to the develop branch and it works now.

**More info on our setup:**
We use the roles and profiles pattern for our Puppet setup. We're including the puppet-snmp in our base class which is called profile::base.

The puppet-snmp module tests run fine on their own. When I include it in our base class and run the rspec tests it fails with that String comparison error.

My computer where I'm running the Rspec test for profile:base which includes puppet-snmp.
ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.1.0], Puppet 3.7.4, rpsec (3.2.0), rspec-puppet 2.0.1.

**I'm defining the following facts at the top of my test**
let(:facts) do {
:hostname => 'ios2',
:osfamily => 'RedHat',
:operatingsystem => 'RedHat',
:operatingsystemrelease => '6.3',
:operatingsystemmajrelease => '6',
}

**And running this in my test**
context 'with defaults for all parameters' do
it { is_expected.to create_class('profile::base') }
it { should contain_class('nrpe') }
it { should contain_class('snmp') }
end

**Inside my base.pp**
 class { '::snmp':
    agentaddress => hiera_array('profile::base::snmp_agentaddress',undef),
    ro_network   => hiera_array('profile::base::snmp_ronetwork'),
    ro_community => hiera('profile::base::snmp_rocommunity'),
    snmpd_config => hiera_array('profile::base::snmp_config',[]),
 }

Then I get the error Puppet::Error:comparison of String with 5 failed at.

**Comment by phathocker** [comment]
@razorsedge I'm getting this too on ruby 1.9.3-p551 and 2.1.5.  The code works fine but the test using <code>FUTURE_PARSER=yes rake spec_clean; rake spec</code> fails in my roles/profiles also.

<pre><code>
  2) roles supported operating systems roles class without any parameters on RedHat should contain Class[roles]
     Failure/Error: it { should contain_class('roles') }
     Puppet::Error:
       comparison of String with 5 failed at /home/myuser/src/r10k_devel/roles/spec/fixtures/modules/snmp/manifests/params.pp:293 on node localhost.localdomain
     # /home/myuser/.rvm/gems/ruby-1.9.3-p551@pe-04202015/gems/puppet-3.7.5/lib/puppet/parser/ast/comparison_operator.rb:28:in `<='
     # /home/myuser/.rvm/gems/ruby-1.9.3-p551@pe-04202015/gems/puppet-3.7.5/lib/puppet/parser/ast/comparison_operator.rb:28:in `evaluate'
     # /home/myuser/.rvm/gems/ruby-1.9.3-p551@pe-04202015/gems/puppet-3.7.5/lib/puppet/parser/ast.rb:61:in `safeevaluate'
</code></pre>

The spec for the class is still very generic:

<pre><code>
→ cat spec/classes/example_spec.rb 
require 'spec_helper'

describe 'roles' do
  context 'supported operating systems' do
    ['RedHat'].each do |osfamily|
      describe "roles class without any parameters on #{osfamily}" do
        let(:hiera_config) { 'spec/fixtures/hiera/hiera.yaml' }
        let(:params) {{ }}
        let(:facts) {{
          :osfamily => osfamily,
          :operatingsystem => osfamily,
          :operatingsystemmajrelease => '6',
          :concat_basedir => '/tmp'
        }}

        it { should compile.with_all_deps }
        it { should contain_class('roles') }
      end
    end
  end
end
</code></pre>

I am using these gems if that helps:

<pre>
hiera (1.3.4)
metadata-json-lint (0.0.6)
puppet (3.7.5)
puppet-blacksmith (3.3.1)
puppet-lint (1.1.0)
puppet-syntax (2.0.0)
puppetlabs_spec_helper (0.10.2)
rake (10.4.2, 0.9.2.2)
rspec (3.2.0)
rspec-core (3.2.3)
rspec-expectations (3.2.1)
rspec-its (1.2.0)
rspec-mocks (3.2.1)
rspec-puppet (2.0.1)
rspec-support (3.2.2)
</pre>

**Comment by deepakhj** [comment]
@phathocker Try this:

```
    :operatingsystemrelease     => 6.3,
    :operatingsystemmajrelease  => 6,
```

**Comment by phathocker** [comment]
@deepakhj - Thanks!  The operatingsystemrelease was missing and causing my problem!

**Pull request closed without merging**
